# Generated by Django 4.1.4 on 2023-02-15 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(default=django.utils.timezone.now, null=True)),
                ('checkout', models.DateField(default=django.utils.timezone.now, null=True)),
                ('noad', models.CharField(max_length=20)),
                ('nokid', models.CharField(max_length=20)),
                ('booking', models.CharField(max_length=20)),
                ('food', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
